### ISSUE TITLE
ability to build a host

### ISSUE THREAD

**Issue by nesanton** [theforeman/foreman-ansible-modules#402]
##### SUMMARY
When creating a host via API one can pass ```build: true```. This will setup all the necessary context required to build/provision this host. If this host is powered on within build token lifetime - it will get booted from PXE and installed according to context and settings of the host group it belongs to.

foreman_host does not seem to provide such an option.
Have I missed somthing?

In case there's indeed no such feature at the moment I can suggest a couple of options on how to add it:

1. Add a boolean ```build``` argument to the foreman_host module. In case the build token exists and has not expired yet, the module would not change anything on existing host. Otherwise, if host exists, but build token does not - the module would update the host, resulting in ```changed: true```

2. Add foreman_host_build module that does does the same as above but with its own idempotency logic, not affecting the idempotent behavior of the foreman_host module.

If you like I can try developing either of these two or other solution that you see fit.

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment]
Hi,

no, you didn't miss anything. The `foreman_host` is pretty low on features today, which is mainly because a Host in Foreman can be *very* complicated and we wanted to have *something* to begin with (see https://github.com/theforeman/foreman-ansible-modules/issues/256 for a longer discussion on that topic).

The host, as created today by the module, does not have enough information to go into build mode, so just adding a `build` param to the module probably won't cut it -- unless you want to use the module to trigger the build mode, but actually define the host using hammer/UI.

Additionally, the module is still using the nailgun library, not apypie, so I think it should be migrated first before extending it further.

As to your question about same or separate module: Given `build` is a param you give to the regular host create/update API call, I think it's fine to add build to the existing module -- in contrast to foreman_host_power which talks to a different API endpoint for the power state.

**Comment by evgeni** [comment]
cc @Fobhep as the original author of the module

**Comment by nesanton** [comment]
@evgeni,

As long as the host_group is prefilled with all the necessary processioning context, simply adding ```build: yes``` would do the job.

I migrated the module to apypie and also added the ```build``` option.
PR will follow. I tried to keep everything as close as possible to the original module's logic.
@Fobhep, please have a look if that's ok with you.

Known issues (or features):
* ```name``` has to be specified without domain part
Not sure if that's how it should be, but I decided not to change the behavior of the original module just yet. If there is no domain defined in the ```hostgroup```, module will fail due to RFC in-compliant name (ending with period), which was also the case in the original module.
* ```hostgroup``` is required. It makes sense up until this module gets all the possible individual parameters for a host
