### ISSUE TITLE
How to read an entity?

### ISSUE THREAD

**Issue by sean797** [theforeman/foreman-ansible-modules#406]
##### SUMMARY
Currently, users can use `foreman_search_facts` for searching entities. As this only returns the fields that the Foreman API returns during the search users need a way to read all attributes of an entity. For example, how do I see locations that a domain is associated with?

I think I see 3 possible solutions (please suggest more if you can):

1. Create a `*_facts` module for every module. I don't really like this due to the effort required to create and maintain these.
2. Have `foreman_search_facts` also read each result it finds. Potentially slow?
3. Make every module also return the entity that it created/found/modified.

Personally, I think I prefer 3. Please weigh in folks

@nstrug and I spoke about this yesterday.

##### ISSUE TYPE
 - Feature Idea

**Comment by mdellweg** [comment]
I kind of did something like 3 with the settings_module a long time ago. And i'd like to promote this.
I hope, it does not interfere with the planned 'diff'-support.

**Comment by evgeni** [comment]
I think this issue is twofold.

1. When we create/update an entity, we should return the new entity to Ansible (we don't do this atm, besides what @mdellweg did in the one module).
2. When we use `foreman_search_facts`, we don't create/update anything, so there is "nothing" to return, so we return what the API gave us for the search and that might be not sufficient in some cases.

To fix 2, shall we add a `recursive` or `deep` or whatever flag to `foreman_search_facts`, that will try to read all details of the results? That way the user has the choice of all vs slow?

**Comment by nstrug** [comment]
I suggest you use ```info``` as the flag to ```foreman_search_facts``` - this would then be analogous to e.g. ```hammer domain info...```

**Comment by evgeni** [comment]
see #412 for a possible fix

**Comment by evgeni** [comment]
(I used `full_details` with a `info` alias)

**Comment by evgeni** [comment]
fixed in #412
