### ISSUE TITLE
Add Mac Address/IP etc in the foreman_host module

### ISSUE THREAD

**Issue by itcultus** [theforeman/foreman-ansible-modules#586]
##### SUMMARY
Currently, the `foreman-host` module supports only a limited set of options for the host creation. 
While a lot of the options are supported by the hostgroup, other (very important ones) are not. 

##### ISSUE TYPE
What I would like to have is: 

* Ask for the interface information (name, mac, IP, etc)
* Ask for the root password 
* Ask for the Owner of the host (really critical for SSH key distribution)

**Comment by evgeni** [comment]
Hi,

this is correct, a longish explanation on why this is like it is (today) can be found in https://github.com/theforeman/foreman-ansible-modules/issues/256 which I think this issue is a duplicate of.

We should start porting the hostgroup functionality back to host, but so far noone did the work :(

**Comment by evgeni** [comment]
Hey @itcultus 

I have implemented ip, mac, password, comment and owner in https://github.com/theforeman/foreman-ansible-modules/pull/696

would you mind having a look and tell us if that's sufficient for your usecase? I know, that's still not *ALL* params for host, but at least more :)
