### ISSUE TITLE
Define and update minimal supported Ansible release

### ISSUE THREAD

**Issue by evgeni** [theforeman/foreman-ansible-modules#620]
We currently document that the modules *should* work with Ansible 2.3+, but only really test 2.7+.

Ansible itself also [only supports the last 3 versions](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html) (so 2,7, 2.8 and 2.9 at the time of writing).

We have multiple issues/PRs open that would bump our minimum version to 2.8: https://github.com/theforeman/foreman-ansible-modules/issues/399, https://github.com/theforeman/foreman-ansible-modules/pull/328, https://github.com/theforeman/foreman-ansible-modules/issues/326

While I don't think we should bump the minimal version to 2.8 just yet, I think it is time to document that we only support 2.7+ and follow Ansible's rule to support only the last three stable versions in the future.

This was also briefly mentioned in https://github.com/theforeman/foreman-ansible-modules/issues/599 (even tho it  was off-topic there).

**Comment by bagasse** [comment]
I think we can document that we support all Ansible supported versions with a link to Ansible documentation where are documented currently supported versions, and that older Ansible version may work but are not tested.

When 2.8 will be the older supported version (and all PR that requires 2.8+ are merged), we change the docs to mention that it will not work with Ansible < 2.8 because we use functionality that are 2.8+.
