### ISSUE TITLE
Rename katello_sync to repository_sync, katello_upload to content_upload and foreman_environment to puppet_environment

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-ansible-modules#832]
Related to dropping `katlelo_` from modules to rely on the namespace, `sync` would be too generic and thus renaming to something that reflects what is being synced makes more sense.

**Comment by evgeni** [comment]
Does the same apply for `upload`?

**Comment by sean797** [comment]
or just `sync` so `theforeman.foreman.sync` which I slightly lean towards but I think either choice is fine.

**Comment by evgeni** [comment]
@sean797 I think with "sync" the question is "sync what?" as there are multiple things to sync, repos, templates. Given we have a template sync one that's called template_sync, I'd lean towards repository_sync.

**Comment by evgeni** [comment]
Oh, and in hammer it's "hammer repository sync" or "hammer product sync" (to sync all of a product). As we don't want to split (I think?), repository is nicer than product.

Oh and content is not specific enough I think.

**Comment by ehelms** [comment]
Yes to upload. And yes, no need to split unless its cleaner interface for user.

**Comment by evgeni** [comment]
So, upload what? content_upload? (After I veto-ed content_sync?)

**Comment by ehelms** [comment]
Yes.

**Comment by mdellweg** [comment]
I read `repository_sync` and `content_upload` now, and i can ack those.

`upload` really takes single files of _content_ so that name sounds right to me.
On the other hand what we _sync_ are _repositories_ and specifying a _product_ to hit a multitude of them is more like a convenience feature to me.

**Comment by sean797** [comment]
> @sean797 I think with "sync" the question is "sync what?" as there are multiple things to sync, repos, templates

That's true... let's kill `sync`.

**Comment by evgeni** [comment]
Another module we will need a new name for is `environment`. Not because it's a bad name, but because you can't call a module `environment` -- that keyword is reserved for the actual environment of the task.

And yes, often the modules will be called as `theforeman.foreman.environment` and that'll work, you can specify a `collections` param in a playbook, to avoid to spell out the collection name all the time, and then you end up writing plain `environment` again. How about `puppet_environment`, because it's really that, Puppet?
